import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/app/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang='en'>
    <body suppressHydrationWarning={true} >
      <div className={inter.className} >
        {children}
        <Footer />
      </div>
    </body>
  </html>
);

export default RootLayout;